name: C/C++ CI

on:
  push:
    branches: [ 'jpreprocess', '1.11']
  pull_request:
    branches: [ 'jpreprocess', '1.11' ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CC: gcc
      CXX: g++

    steps:
      - uses: actions/checkout@v2
        with:
          repository: r9y9/hts_engine_API
          path: hts_engine_API
      - name: Build hts_engine_API
        working-directory: ./hts_engine_API/src
        run: |
          cmake -D CMAKE_BUILD_TYPE=Release -D BUILD_SHARED_LIBS=ON -S . -B build
          cmake --build build --config Release
      - uses: actions/checkout@v2
        with:
          path: open_jtalk
      - name: Build open_jtalk
        working-directory: ./open_jtalk/src
        run: |
          cmake -D CMAKE_BUILD_TYPE=Release -D BUILD_SHARED_LIBS=ON -D CMAKE_INCLUDE_PATH=../../hts_engine_API/src/include -D CMAKE_LIBRARY_PATH=../../hts_engine_API/src/build/lib -S . -B build
          cmake --build build --config Release
      - name: Debug
        run: |
          ls -l ./open_jtalk/src/build/
